= Privacy Policy
Fin Reinhard <mail@angu.li>
v1.0, 2020-06-20

The following privacy policy applies to the iOS and Android app &quot;MaxOut&quot;, in the following as MaxOut or the app, developed by Fin Reinhard and the website https://maxout.angu.li/[maxout.angu.li].
This privacy policy is also available at https://maxout.angu.li/privacy[maxout.angu.li/privacy].

In the following we have collected some questions about privacy collected and answered.
Feel free to contact us at mailto:mail@angu.li[mail@angu.li] when the list is incomplete.

== What data collects the app?

The app only stores the data you put in to provide a smooth user experience.
Here is what the app stores:

1. Your Skill configuration like the name.
2. Your Set Data, including amount of repititions and the current timestamp.

Usually this data cannot be directly associated with your person.

== Where stores the app the data?

Your data will only be stored and processed on your device.

== How tracks the app me?

The app has no analytics software built in, so you can stay anonymous and enjoy the app with the highest standard of privacy.
We won't even notice you are using the app, so if you enjoy it and want to give us some feedback, you can leave a review on the AppStore.

== How can I delete my data?

At all times you have the full control about your data.
In the settings we provide you the option to delete all data, that is stored by the app.

WARNING: Once you delete your data, there is no way back!
